# Setup
title:        Autumn Wind Blog
tagline:      从来没有一个屌丝可以逆袭
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       XianHui
  url:        https://zxhio.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
