# Setup
title:        zxh's blog
tagline:      咸鱼 360° 翻身
baseurl:      ""
paginate:     2

# About/contact
author:
  name:       zxh
  url:        https://zxhio.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
